package com.akingyin.rfidwgs.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.akingyin.rfidwgs.db.Batch;
import com.akingyin.rfidwgs.db.BleDeviceRepairInfo;
import com.akingyin.rfidwgs.db.LatLngRfid;

import com.akingyin.rfidwgs.db.dao.BatchDao;
import com.akingyin.rfidwgs.db.dao.BleDeviceRepairInfoDao;
import com.akingyin.rfidwgs.db.dao.LatLngRfidDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig batchDaoConfig;
    private final DaoConfig bleDeviceRepairInfoDaoConfig;
    private final DaoConfig latLngRfidDaoConfig;

    private final BatchDao batchDao;
    private final BleDeviceRepairInfoDao bleDeviceRepairInfoDao;
    private final LatLngRfidDao latLngRfidDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        batchDaoConfig = daoConfigMap.get(BatchDao.class).clone();
        batchDaoConfig.initIdentityScope(type);

        bleDeviceRepairInfoDaoConfig = daoConfigMap.get(BleDeviceRepairInfoDao.class).clone();
        bleDeviceRepairInfoDaoConfig.initIdentityScope(type);

        latLngRfidDaoConfig = daoConfigMap.get(LatLngRfidDao.class).clone();
        latLngRfidDaoConfig.initIdentityScope(type);

        batchDao = new BatchDao(batchDaoConfig, this);
        bleDeviceRepairInfoDao = new BleDeviceRepairInfoDao(bleDeviceRepairInfoDaoConfig, this);
        latLngRfidDao = new LatLngRfidDao(latLngRfidDaoConfig, this);

        registerDao(Batch.class, batchDao);
        registerDao(BleDeviceRepairInfo.class, bleDeviceRepairInfoDao);
        registerDao(LatLngRfid.class, latLngRfidDao);
    }
    
    public void clear() {
        batchDaoConfig.clearIdentityScope();
        bleDeviceRepairInfoDaoConfig.clearIdentityScope();
        latLngRfidDaoConfig.clearIdentityScope();
    }

    public BatchDao getBatchDao() {
        return batchDao;
    }

    public BleDeviceRepairInfoDao getBleDeviceRepairInfoDao() {
        return bleDeviceRepairInfoDao;
    }

    public LatLngRfidDao getLatLngRfidDao() {
        return latLngRfidDao;
    }

}
